### ISSUE TITLE
Add local tests to project

### ISSUE THREAD

**Issue by Irineu333** [NeoA11y/SpeakTouch#47]
Study a way to automate testing.

**Comment by Irineu333** [comment]
I was unsuccessful on my first attempt, the Android accessibility API is very difficult to test.

**Comment by Irineu333** [comment]
I was able to add local tests using [Robolectric](https://robolectric.org/) to simulate the Android framework APIs.

**Comment by PatrykMis** [comment]
Robolectic seams to be the most reasonable approach. Here we have TalkBack tests which were using similar approach past days: <https://github.com/google/talkback/tree/12bdf2063e121a021f050c94cf5ebb2489c8af8a/src/test/java/com/android/talkback>.

**Comment by Irineu333** [comment]
@PatrykMis I didn't find automated testing in the mentioned link. Just a manual testing application.

**Comment by PatrykMis** [comment]
I apologise, You're absolutely right. Of course I ment <https://github.com/google/talkback/tree/12bdf2063e121a021f050c94cf5ebb2489c8af8a/src/test/java/com/android/talkback>.

**Comment by Irineu333** [comment]
Interesting, I will use it for study, it can help in other tests.
